name: CI-CD for function1

on:
  push:
    branches:
      - "master"
      - "develop"
    paths:
      - "function1/**"
  pull_request:
    branches:
      - "master"
      - "develop"
    paths:
      - "function1/**"

jobs:
  build_and_test:
    name: "Build and test (Main flow)"
    uses: ./.github/workflows/reusable-build-test.yml
    with:
      function-path: "function1"
  deploy-dev:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    needs: build_and_test
    environment:
      name: development
      url: https://your-development-url.com
    steps:
      - uses: actions/checkout@v4
      - id: "auth-to-google-cloud"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ secrets.PROJECT_ID }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 363.0.0"
      - name: Build shared packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m build
          mkdir function1/dist
          cp dist/shared-0.0.1.tar.gz function1/dist/
      - name: "Deploy"
        uses: "google-github-actions/deploy-cloud-functions@v3"
        timeout-minutes: ${{ secrets.TIMEOUT_MINUTES }}
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          name: "function1Dev"
          region: "asia-northeast1"
          source_dir: "function1"
          runtime: "python310"
          entry_point: "function1"
          service_timeout: "3600"
          environment_variables: |-
            MAX_RETRIES=${{ secrets.FUNCTION1_MAX_RETRIES }}
