name: CI-CD for function1

on:
  push:
    branches:
      - "master"
      - "develop"
    paths:
      - "function1/**"
  pull_request:
    branches:
      - "master"
      - "develop"
    paths:
      - "function1/**"

jobs:
  build_and_test:
    uses: "enjo-kangeki/multiple-repo/workflows/reusable-build-test.yml"
    with:
      function-path: "function1"
