name: CI-CD for function3

on:
  push:
    branches:
      - "main"
      - "develop"
    paths:
      - "function3/**"
  pull_request:
    branches:
      - "main"
      - "develop"
    paths:
      - "function3/**"

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          mkdir -p function3/dist
          cp -r dist/shared-0.0.1.tar.gz function3/dist
          cd function3
          pip install -r requirements.txt
      - name: Install pytest
        run: |
          pip install pytest
      - name: Run unit tests
        run: |
          pytest function3/tests