name: Build and Test function4

on:
  push:
    branches:
      - "main"
      - "develop"
    paths:
      - "function4/**"
  pull_request:
    branches:
      - "main"
      - "develop"
    paths:
      - "function4/**"


jobs:
  unittest_for_function4:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          mkdir -p function4/dist
          cp -r dist/shared-0.0.1.tar.gz function4/dist/
          cd function4
          pip install -r requirements.txt
      - name: Check function run unittest
        uses: actions/checkout@v4
      - name: Install pytest
        run: |
          pip install pytest
      - name: Run unit tests
        run: |
          pytest tests
