name: Build and Test function2

on:
  push:
    branches:
      - "main"
      - "develop"
    paths:
      - "function2/**"
  pull_request:
    branches:
      - "main"
      - "develop"
    paths:
      - "function2/**"


jobs:
  unittest_for_function2:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cp dist/shared-0.0.1.tar.gz function2/dist
          cd function2
          pip install -r requirements.txt
      - name: Check function run unittest
        if: contains(github.event.head_commit.files, 'function2/')
        uses: actions/checkout@v4
      - name: Install pytest
        run: |
          pip install pytest
      - name: Run unit tests
        run: |
          pytest tests
