name: CI-CD for function2

on:
  push:
    branches:
      - "master"
      - "develop"
    paths:
      - "function1/**"
  pull_request:
    branches:
      - "master"
      - "develop"
    paths:
      - "function1/**"

jobs:
  call_reusable_workflow:
    uses: ./.github/workflows/base-build-test.yml
    with:
      function-path: "function1"
