name: CI-CD for function1

on:
  push:
    branches:
      - "main"
      - "develop"
    paths:
      - "function1/**"
  pull_request:
    branches:
      - "main"
      - "develop"
    paths:
      - "function1/**"

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          mkdir -p function1/dist
          cp -r dist/shared-0.0.1.tar.gz function1/dist
          cd function1
          pip install -r requirements.txt
      - name: Install pytest
        run: |
          pip install pytest
      - name: Run unit tests
        run: |
          pytest function1/tests
  deploy:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    needs: build_and_test
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4
      - id: "auth-to-google-cloud"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: "google-github-actions/setup-gcloud@v2"
        with:
          version: ">= 363.0.0"
          project_id: ${{ secrets.PROJECT_ID }}
          credentials_file_path: ${{ steps.auth-to-google-cloud.outputs.credentials_file_path }}
      - name: "Use gcloud CLI"
        run: "gcloud info"
